### ISSUE TITLE
Additional endpoint needed

### ISSUE THREAD

**Issue by cwdcwd** [topcoder-platform/submissions-api#1]
We need one more endpoint added to the swagger and the build to accommodate file uploads as submissions. This should be a `POST` like the existing submission posting event but take a file in as the submission.

**Comment by callmekatootie** [comment]
@cwdcwd Where should the file be uploaded to?

**Comment by callmekatootie** [comment]
The current POST /submissions api appears to take in the URL where the file was uploaded: https://tc-submission-api-dev.herokuapp.com/docs/#!/Submissions/createSubmission

Does that not meet the requirement? I am guessing here that the file is uploaded initially to the cloud, the url of this which is then passed to the above.

This ticket is asking for an endpoint to upload the file to the cloud itself? Could we not just have a single endpoint? I mean we could update existing POST /submissions to take file instead of the url?

**Comment by callmekatootie** [comment]
> For url subs, a processor will go fetch and down load the file to s3.

Should I update existing POST /submission to download the file mentioned in the url to S3, in addition to providing the new endpoint as well?

**Comment by cwdcwd** [comment]
No. The processor will do that after the post event.

**Comment by callmekatootie** [comment]
Stupid question, but this endpoint will only take in the file right? I mean will it also take in the `challengeId`, `memberId` etc? (I am confused about the bit if its possible to send more attributes other than the file, I am inclined to say its not but just being sure)

**Comment by callmekatootie** [comment]
[Reference](https://stackoverflow.com/questions/10899384/uploading-both-data-and-files-in-one-form-using-ajax). I think I may be wrong. It is indeed possible to submit both file and data at the same time.

So, to reframe my question - should the endpoint only accept file or the other attributes too

**Comment by cwdcwd** [comment]
it should take the other attributes so that we know what to put in the db when it logs the uploaded file's URL

**Comment by callmekatootie** [comment]
Contest has been created - https://www.topcoder.com/direct/contest/detail?projectId=30066809

**Comment by cwdcwd** [comment]
thanks @callmekatootie !

**Comment by callmekatootie** [comment]
@cwdcwd Pull Request ready for your review - https://github.com/topcoder-platform/submissions-api/pull/2

**Comment by callmekatootie** [comment]
This ones merged in so closing this.
