### ISSUE TITLE
Error when attempting to pull submissions for draft challenge

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/submissions-api#200]
Is there any reason why we might see this error?

![101112047-11719d80-360f-11eb-9ede-658302c827ff](https://user-images.githubusercontent.com/21790/101119532-a42a3080-363f-11eb-9be7-7ec862c4d59f.png)

**Comment by callmekatootie** [comment]
@jmgasper Could you share that challenge id so that I can easily copy it

**Comment by jmgasper** [comment]
@callmekatootie - I've asked the dev to provide it, thanks!

**Comment by callmekatootie** [comment]
No that's ok... I'll type it over... Was looking for a quicker approach :)

**Comment by callmekatootie** [comment]
@jmgasper There does not seem to be a legacyId for that challenge. Not saying that is the cause of it but that does seem suspect.

Trying to get hold of the dev logs to see if I am right - facing some issues. Checking with the devops team...

Will keep you posted

**Comment by jmgasper** [comment]
@callmekatootie -` f48ee070-9afd-4876-bf7b-53e9594d2d7f`

**Comment by callmekatootie** [comment]
@jmgasper I am still trying to get my hands on the logs but here is my observation:

- the challenge id is a v5 challenge id. Submission API only works with legacy challenge id and thus, it attempts to retrieve the legacy challenge id
- This attempt should fail, because from what I see, GET `https://api.topcoder-dev.com/v5/challenges/f48ee070-9afd-4876-bf7b-53e9594d2d7f` does not return the legacy id for that challenge
- My guess is because the challenge is in draft status and not active.

Could you request the developer to activate the contest or use a contest that is active and then verify if they face the same issue.

I tried using a contest that was active and did not get any error

**Comment by callmekatootie** [comment]
@jmgasper Did the above approach work?

**Comment by callmekatootie** [comment]
Closing due to non activity. Please reopen if the issue persists.
