### ISSUE TITLE
Update ES for each Create/Update/Delete event

### ISSUE THREAD

**Issue by BadalZ** [topcoder-platform/submissions-api#53]
We need to remove data latency to avoid misconfiguration in other system and as part of that change we have finalised to do the below changes.

Instead, We need to Update ES for each Create/Update/Delete events just after DB operation from Submission API itself.

So each Create update or delete operation will be perform on database first and then it will do the ES operation.

**Comment by sharathkumaranbu** [comment]
@BadalZ Yesterday @cwdcwd and me were fixing an issue with Submission-processor-es.

After uploading a submission, There are two updates happening in parallel. One will be from legacy-submission-processor and one will be from AV Scan.

ES will not handle parallel updates and it will reject one of the updates. We have fixed the issue by setting the concurrency to 1 so that `submission-processor-es` will process the update in parallel.

If we move the ES update to Submission API, Probable chances are that both legacy-submission-processor and AV Scan will try to update at the same time via Submission API and Submission API will process the update in parallel and one update will get rejected.

Either we have to stick to the current solution or bring some retry mechanism in Submission API

**Comment by callmekatootie** [comment]
Perhaps we look into checking the version of the document before updating: https://www.elastic.co/guide/en/elasticsearch/guide/current/optimistic-concurrency-control.html. Thoughts?

**Comment by sharathkumaranbu** [comment]
@callmekatootie When there are two updates happening in parallel, We may end up in a situation where we are trying to update the same version.

Request A:

Read ES for the version. Version will be 1

Request B:

Read ES for the version. Version will be 1 again because the Request A & B are running in parallel, Only when the Request A / B completes, Version number will be updated else Version will remain the same for both the requests

Hence the request will fail even if we read the version and etc..

**Comment by sharathkumaranbu** [comment]
@callmekatootie @BadalZ @cwdcwd May be we can use something like this (https://www.npmjs.com/package/better-queue) to control parallel updates to the same ID. Yet to be tested.

**Comment by sharathkumaranbu** [comment]
No longer a choice I believe. Everything is handled via ES Processor only.
