### ISSUE TITLE
Submissions are not working for V4 updates

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/submissions-api#92]
Submissions are not working for Direct-MM (subTrack: "DEVELOP_MARATHON_MATCH") type

_For V4 updates : Community App:mm-develop-merge branch and Challenge API : mm-feature branch_

**On Beta Production**
https://beta-community-app.topcoder.com/challenges/30073855/submit
http://api.topcoder.com/v4/challenges/30073855

**Also, on test development** 
https://test-community-app.topcoder-dev.com/challenges/30054163/submit
http://api.topcoder-dev.com/v4/challenges/30054163

**Console message is :** 

`{"message":"Cannot read property 'allPhases' of undefined"}`

**Comment by callmekatootie** [comment]
The cause of the issue appears to be the challenge api, at least in dev

**In Dev**
http://api.topcoder-dev.com/v4/challenges/30054163 appears to work but https://api.topcoder-dev.com/v3/challenges?filter=id=30054163 does not.

**In Beta Prod**
@sushilshinde Not sure what the issue is here. Are you getting the same message here too? Cause http://api.topcoder.com/v4/challenges?filter=id=30073855 does seem to return results properly. I cannot imagine why it says `allPhases of undefined` in this case... Could you try again in prod?

We are using the latter api and not the former one for getting challenge details since the latter one provides some additional info that the former one does not.

**Comment by callmekatootie** [comment]
Cause of issue found over slack - v4 challenge api has the details. Submission api however is using v3 challenge api

**Comment by sushilshinde** [comment]
This will work 

https://api.topcoder-dev.com/v3/challenges/30054163

instead of 

https://api.topcoder-dev.com/v3/challenges?filter=id=30054163 

@callmekatootie

**Comment by callmekatootie** [comment]
I just checked and it appears we should not face any issue in using v4. No changes are needed to the api, besides updating the config.

Feature branch https://github.com/topcoder-platform/submissions-api/tree/v4_challenge created that contains the v4 branch in the config

**Comment by sushilshinde** [comment]
Working now
